apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "donate4fun.fullname" . }}
  labels:
    {{- include "donate4fun.labels" . | nindent 4 }}
spec:
  domains:
  - {{ .Values.ingress.host }}
