{{- if .Values.ingress.enabled -}}
{{- $fullName := include "donate4fun.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "donate4fun.labels" . | nindent 4 }}
  annotations:
  {{- if eq .Values.ingress.className "gce" }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
    networking.gke.io/v1beta1.FrontendConfig: {{ $fullName }}
    networking.gke.io/managed-certificates: {{ $fullName }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              name: http-backend
      - path: /sitemap.xml
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              name: http-backend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              name: http-frontend
---
{{- if eq .Values.ingress.className "gce" }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ $fullName}}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT
{{- end }}
{{- end }}
