apiVersion: v1
kind: Secret
metadata:
  name: {{ template "donate4fun.fullname" . }}
  labels:
    app: {{ template "donate4fun.name" . }}
    chart: {{ template "donate4fun.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: generic
stringData:
  service-account.json: |
{{ toJson .Values.backend.serviceAccount | indent 4 }}
