apiVersion: v1
kind: Service
metadata:
  name: {{ include "donate4fun.fullname" . }}
  labels:
    {{- include "donate4fun.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "donate4fun.fullname" . }}"}'
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: http-backend
    protocol: TCP
    name: http-backend
  - port: {{ .Values.frontend.port }}
    targetPort: http-frontend
    protocol: TCP
    name: http-frontend
  selector:
    {{- include "donate4fun.selectorLabels" . | nindent 4 }}
{{- if eq .Values.ingress.className "gce" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "donate4fun.fullname" . }}
spec:
  logging:
    enable: true
{{- end }}
