# Default values for rtl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nikicat/rtl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  digest: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  accessMode: ReadWriteOnce
  size: 5Gi

config:
  defaultNodeIndex: 1
  port: 80
  multiPassHashed: 85fd7c889f71cf105375595cddc06b9d38fc562cb69c54f8c165aa751d81b3d9
  SSO:
    rtlSSO: 0
    rtlCookiePath: ''
    logoutRedirectLink: ''
  nodes:
  - index: 1
    lnNode: mainnet
    lnImplementation: LND
    Authentication:
      macaroonPath: "/fake-macaroon"
    Settings:
      userPersona: MERCHANT
      themeMode: NIGHT
      themeColor: PURPLE
      channelBackupPath: "/rtl-backup"
      logLevel: ERROR
      lnServerUrl: http://lnd-prod.lnd-prod
      fiatConversion: true
      currencyUnit: EUR
