apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lnd.fullname" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  lnd.conf: |
    wallet-unlock-password-file=/secret/wallet.pw
    wallet-unlock-allow-create=1
{{ .Values.lnd.config | indent 4 }}
