apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lnd.fullname" . }}
  labels:
    app: {{ include "lnd.name" . }}
    chart: {{ include "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: generic
stringData:
  wallet.pw: {{ .Values.lnd.walletPassword | quote }}
