apiVersion: v1
kind: Service
metadata:
  name: {{ template "lnd.fullname" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: rpc
    port: {{ .Values.services.rpcPort }}
    targetPort: rpc
  - name: rest
    port: {{ .Values.services.restPort }}
    targetPort: rest
  - name: p2p
    port: {{ .Values.services.p2pPort }}
    targetPort: p2p
  selector:
    app: {{ template "lnd.name" . }}
    release: {{ .Release.Name }}
