version: "3.9"

x-common-lnd: &clnd
  user: ${UID}:${GID}
  privileged: true
  build:
    context: ./lnd
    args:
      GIT_REPO: https://github.com/nikicat/lnd
      #GIT_REF: abaef4f8c14be17998566d4cacdc25f1ec585101
      #GIT_REF: v0.15.5-beta.rc2
      GIT_REF: 5051c3e295da038431a407880f80996eb6493b7e
  command:
  - /entrypoint.sh
  - --configfile=/lnd-config/lnd.conf
  - --tor.password=${TOR_PASSWORD}
  environment:
  - NEUTRINO_HOST=bitcoind
  - NEUTRINO_PORT=${BITCOIN_PORT}
  depends_on:
  - bitcoind

services:
  bitcoind:
    user: ${UID}:${GID}
    container_name: ${COMPOSE_PROJECT_NAME}-bitcoind
    build: ./bitcoind
    command: [
      "bitcoind",
      "-datadir=/data",
      "-bind=0.0.0.0:${BITCOIN_PORT}",
      "-rpcbind=0.0.0.0:${BITCOIN_RPC_PORT}",
      "-rpcallowip=0.0.0.0/0",
      "-dnsseed=0",
      "-dns=0",
      "-listenonion=0",
      "-txindex=1",
      "-onlynet=ipv4",
      "-regtest=1",
      "-blockfilterindex=1",
      "-peerblockfilters=1",
      "-fallbackfee=0.0002",
      "-wallet=testwallet",
    ]
    ports:
    - "127.0.0.1:${BITCOIN_RPC_PORT}:${BITCOIN_RPC_PORT}"
    - "127.0.0.1:${BITCOIN_PORT}:${BITCOIN_PORT}"
    volumes:
    - ./bitcoind-data:/data

  tor:
    user: ${UID}:${GID}
    container_name: ${COMPOSE_PROJECT_NAME}-tor
    build: ./tor
    volumes:
    - ./tor-data:/var/lib/tor
    - ./tor-config:/tor-config
    ports:
    - "[::1]:${TOR_CONTROL_PORT}:9051"
    - "[::1]:${TOR_SOCKS_PORT}:9050"
    environment:
    - TOR_PASSWORD

  lnd-alice:
    <<: *clnd
    container_name: ${COMPOSE_PROJECT_NAME}-lnd-alice
    volumes:
    - ./lnd-alice:/lnd
    - ./lnd-config:/lnd-config
    ports:
    - "127.0.0.1:10001:${LND_REST_PORT}"
    - "127.0.0.1:20001:${LND_RPC_PORT}"

  lnd-bob:
    <<: *clnd
    container_name: ${COMPOSE_PROJECT_NAME}-lnd-bob
    volumes:
    - ./lnd-bob:/lnd
    - ./lnd-config:/lnd-config
    ports:
    - "10002:${LND_REST_PORT}"
    - "20002:${LND_RPC_PORT}"

  lnd-carol:
    <<: *clnd
    container_name: ${COMPOSE_PROJECT_NAME}-lnd-carol
    volumes:
    - ./lnd-carol:/lnd
    - ./lnd-config:/lnd-config
    ports:
    - "10003:${LND_REST_PORT}"
    - "20003:${LND_RPC_PORT}"

  rtl:
    user: ${UID}:${GID}
    container_name: ${COMPOSE_PROJECT_NAME}-rtl
    build:
      context: ./rtl
      args:
        GIT_REF: ee096d7e1b9b03736fb5317f7355abdab2c6a678
    restart: unless-stopped
    depends_on:
      - lnd-alice
      - lnd-bob
      - lnd-carol
    volumes:
      - ./rtl-config:/config
      - ./rtl-backup:/backup
    ports:
      - "[::1]:${RTL_PORT}:${RTL_PORT}"
    environment:
      RTL_CONFIG_PATH: /config
      PORT: ${RTL_PORT}
