ingress:
  enabled: true
  className: gce
  staticIpName: donate4-fun
  host: donate4.fun
  tls: null

frontend:
  image:
    repository: europe-central2-docker.pkg.dev/donate4fun-prod/docker/donate4fun-frontend

backend:
  image:
    repository: europe-central2-docker.pkg.dev/donate4fun-prod/docker/donate4fun-backend
  config:
    rollbar:
      environment: production
    posthog:
      project_api_key: 'phc_2CphDSfOn61NrqYZnloxHWpwFFjd4mHxUtZwcwrogC0'
      host: 'https://eu.posthog.com'
    google_cloud_logging: true
    db:
      echo: false
      max_overflow: 30
      connect_arg:
        timeout: 1
    hypercorn:
      bind: '[::]'
      use_reloader: false
      websocket_ping_interval: 10
      access_log_format: '%({X-Forwarded-For}i)s "%(R)s" %(s)s %(L)s %(b)s "%(f)s" "%(a)s"'
      include_server_header: false
    youtube:
      refresh_timeout: P1D
    twitter:
      greeting: "Hey! I'm a Donate4Fun Twitter bot. I'll check if you have any tips or donations."
      enable_bot: false
      dm_check_interval: PT20S
      self_id: "1572908920485576704"
      refresh_timeout: P1D
    lnd:
      url: http://lnd-prod.lnd-prod
      lnurl_base_url: https://donate4.fun
    lnurlp:
      min_sendable_sats: 10
      max_sendable_sats: 5_000_000
    min_withdraw: 10
    fee_limit: 10
    withdraw_timeout: 10
    ownership_message: "I confirm that donate 4 fun account {donator_id} could withdraw my donations."
    cookie_domain: donate4.fun
    latest_donations_count: 50
    frontend_port: 80
    api_port: 8080
    release: true
    base_url: https://donate4.fun
    fastapi:
      debug: false
      root_path: ""
    log:
      version: 1
      disable_existing_loggers: false
      formatters:
        std:
          format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      handlers:
        stderr:
          class: logging.StreamHandler
          level: TRACE
          formatter: std
          stream: ext://sys.stderr
      loggers:
        donate4fun:
          level: DEBUG
        sqlalchemy.engine.Engine:
          level: WARNING
        hypercorn:
          level: DEBUG
      root:
        level: DEBUG
        propagate: true
        handlers: [stderr]

cronjobs:
- name: refetch-twitter
  schedule: "37 * * * *"
  func: jobs.refetch_twitter_authors
- name: refetch-youtube
  schedule: "51 * * * *"
  func: jobs.refetch_youtube_channels
