ingress:
  enabled: true
  className: gce
  staticIpName: donate4-fun
  host: donate4.fun
  tls: null

frontend:
  image:
    repository: europe-central2-docker.pkg.dev/donate4fun-prod/docker/donate4fun-frontend

backend:
  image:
    repository: europe-central2-docker.pkg.dev/donate4fun-prod/docker/donate4fun-backend
  config:
    db:
      echo: false
      connect_arg:
        timeout: 1
    hypercorn:
      use_reloader: false
      bind: '[::]:8080'
    youtube:
      oauth:
        redirect_base_url: https://donate4.fun
    lnd:
      url: http://lnd-prod.lnd-prod
      lnurl_base_url: https://donate4.fun
    min_withdraw: 10
    fee_limit: 10
    withdraw_timeout: 10
    fastapi:
      debug: false
      root_path: ""
    log:
      version: 1
      disable_existing_loggers: true
      formatters:
        std:
          format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      handlers:
        stderr:
          class: logging.StreamHandler
          level: DEBUG
          formatter: std
          stream: ext://sys.stderr
      loggers:
        donate4fun:
          level: DEBUG
        vcr:
          level: WARNING
        sqlalchemy.engine.Engine:
          level: INFO
      root:
        level: DEBUG
        propagate: true
        handlers: [stderr]
