ingress:
  host: stage.donate4.fun
  staticIpName: donate4fun-stage

backend:
  config:
    base_url: https://stage.donate4.fun
    twitter:
      enable_bot: false
    rollbar:
      environment: staging
    posthog:
      debug: true
    youtube:
      oauth:
        redirect_base_url: https://stage.donate4.fun
    lnd:
      lnurl_base_url: https://stage.donate4.fun
    log:
      loggers:
        httpx:
          level: INFO
        donate4fun.screenshot:
          level: TRACE
        donate4fun.twitter:
          level: INFO
        posthog:
          level: DEBUG
  resources:
    limits:
      cpu: 250m
      memory: 712Mi
    requests:
      cpu: 250m
      memory: 712Mi

cronjobs: []
