ingress:
  host: stage.donate4.fun
  staticIpName: donate4fun-stage

backend:
  config:
    bugsnag:
      enabled: false
      release_stage: staging
    rollbar:
      environment: staging
    youtube:
      oauth:
        redirect_base_url: https://stage.donate4.fun
    lnd:
      lnurl_base_url: https://stage.donate4.fun
