apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ template "tor.fullname" . }}
parameters:
  type: pd-balanced
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
