# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nikicat/lnd
  tag: latest
  digest: null
  pullPolicy: IfNotPresent

services:
  rpcPort: 10009
  restPort: 80
  p2pPort: 9735

persistence:
  accessMode: ReadWriteOnce
  size: 5Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 250m

# Custom lnd configuration file used to override default lnd settings
lnd:
  alias: My Node
  walletPassword: ""
  config: |
    bitcoin.active=1
    bitcoin.mainnet=1
    debuglevel=info
    bitcoin.node=neutrino
    neutrino.addpeer=faucet.lightning.community
    neutrino.addpeer=lnd.bitrefill.com:18333
    feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json
    protocol.wumbo-channels=1
    tlsautorefresh=1
    no-rest-tls=1
    no-macaroons=1
    lnddir=/lnd
    tor.active=1
    tor.socks=tor-prod.tor-prod
    tor.control=tor-prod.tor-prod
    tor.v3=1
    tor.skip-proxy-for-clearnet-targets=1
    tor.password=123qweasd
