# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nikicat/lnd
  tag: latest
  digest: null
  pullPolicy: IfNotPresent

services:
  rpcPort: 10009
  restPort: 8080
  p2pPort: 9735

persistence:
  accessMode: ReadWriteOnce
  size: 5Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 300m

# Custom lnd configuration file used to override default lnd settings
configurationFile:
  lnd.conf: |-
    bitcoin.active=1
    bitcoin.mainnet=1
    debuglevel=info
    bitcoin.node=neutrino
    neutrino.addpeer=faucet.lightning.community
    neutrino.addpeer=lnd.bitrefill.com:18333
    feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json
    protocol.wumbo-channels=1
    tlsautorefresh=1
    no-rest-tls=1
    no-macaroons=1
    noseedbackup=1
    lnddir=/lnd
    listen=127.0.0.1
    rpclisten=127.0.0.1
    restlisten=127.0.0.1
