api_port: ENC[AES256_GCM,data:FOTRxw==,iv:QMNZf1EXAL6v0olKv1YPbG6nLpPvUzhlNU5ShIloIy0=,tag:P6GeUcrPERLqWaBSG4Tzkw==,type:int]
base_url: ENC[AES256_GCM,data:wWn+FY6HXRkkVDUbEYsBH+ceQg==,iv:3pjJCaNtAn7X4eLWQJaPg158jN95Dzax4Bybrtr5dZY=,tag:YzyoWeXbUh1NWLTF8zR7nQ==,type:str]
cookie_domain: ENC[AES256_GCM,data:NFU3kXap0lqF07g=,iv:ubpPNYuD7W0ck127hJJBXMZx9KYJOZAvxiBakTazF/8=,tag:FB+gIkKhLG1D89jVbIvXtQ==,type:str]
db:
    connect_arg:
        timeout: ENC[AES256_GCM,data:Cg==,iv:U5DYM1qyUJn6O4KJgnBVIyyKrhZIAmZ9Fk7E7FQOoP8=,tag:tBT1OzkafDOom5HlGhsijg==,type:int]
    echo: ENC[AES256_GCM,data:NP0AjPM=,iv:07jkTWFxin6e4B6KhReJ+CFRBit/yuh+RqSkXDjE+0g=,tag:hDcLMUyLKl3WBjdiH/ALew==,type:bool]
    max_overflow: ENC[AES256_GCM,data:378=,iv:PXt9nW2hovCJCVOZ+EVbA4+CJvSC9W0P3Ghj8xtAx5w=,tag:F+6QWKX19NIcPldX8gGQSQ==,type:int]
    url: ENC[AES256_GCM,data:5JideNBZmdrEMz4Tuwnbwk+cgLN9UuRwIt4fd2jT/6p5Vdu3x7IOn0alNm6kVP9nccYpC+51qcU0h8b9,iv:7RqW95QBUfwLLYnKsHULHbV0SzuZ/DEr20SQribKp+k=,tag:GQ/02dPg/jetYPWbqY4L1A==,type:str]
donator_name_seed: ENC[AES256_GCM,data:VYV1ZRE=,iv:wfqd3NoOgSCyLrj5mxURiec3cDZF8gpeDlVkmr8cYAI=,tag:Nio9ta+lQ+xVh6dX+sN9LA==,type:int]
fastapi:
    debug: ENC[AES256_GCM,data:QKtAQMg=,iv:rtepPWtglbIgbIlQYVWu10YUG19KnXkwQ5kcLRBVCW8=,tag:J1hPyjFRdLq7TycHEwrkcg==,type:bool]
    root_path: ""
fee_limit: ENC[AES256_GCM,data:MRk=,iv:oks6Zhkhu3ASb86gHABEOh8j6aRw+aNg+f0HRaYrS8Y=,tag:pqp7an2/qCXxRAS7cQi/gw==,type:int]
frontend_port: ENC[AES256_GCM,data:AFc=,iv:KbMOOo19s5Yc4cg0zvqlIGkNXvUlkOLcgFROZzQdt10=,tag:v9SCOy9lFX+yKLA8vk/AMg==,type:int]
github:
    client_id: ENC[AES256_GCM,data:SA22keDxCf6FXE1BQC95Em7YJjI=,iv:krV3XGqWGJY60g4xJTwQTNE6g8cD8gB2THxPeqkLZ5k=,tag:/618hrZhmxlXHrqVo/Qnng==,type:str]
    client_secret: ENC[AES256_GCM,data:atlNNemHLuNWoS6d7sHNuLjz05nnxOtgZXG4XqpiuV28AuqgDIeKvg==,iv:qJqf2oZghQVLDvhqIA2OhEkcNOooh6O1kawXPTd19YQ=,tag:nxNUMn8phA8WTUZ6R44N6g==,type:str]
google_cloud_logging: ENC[AES256_GCM,data:9oSd4Ew=,iv:NwmVaFoBHcJM60Kb2MK4RcYzoS/+n1Q90KkWjo5y5f0=,tag:Jtr4sfXdgbL/HplvTofZVA==,type:bool]
hypercorn:
    access_log_format: ENC[AES256_GCM,data:7UzpMBuCpwUifC3d8w5elAHjgWZGMvLLHVexyfHBq1NGxH5m7N3K9KaX90/2PCO0o7DKVLAMvYerTPfW/aX7pA==,iv:AYZCyRDSmCYEH3T8Q0XZCLCESFEsHpkCfqS0S9cRhJI=,tag:IqwyX+lzhD6GbG8sQJFEqQ==,type:str]
    bind: ENC[AES256_GCM,data:ki8GOQ==,iv:huekP625hmDmgIDlyzcMY1wCFsmzDMgG0luK2TXLBr8=,tag:rr/0UchjzUvaYSRZoeUEng==,type:str]
    include_server_header: ENC[AES256_GCM,data:x1BVRdQ=,iv:QbInpM5SOag+/tIM2Fm8D0GWIY4n8IhQTbUYrUfatFQ=,tag:iS6HCJqBLeCkWpCN6BkRUA==,type:bool]
    use_reloader: ENC[AES256_GCM,data:gU6pwGA=,iv:0z6qwRh/FU6lrg6H6/NpoBmus01b7ZC//zEXhELnFDE=,tag:Sg/ZSmiHMSrcqWep5VW8Tw==,type:bool]
    websocket_ping_interval: ENC[AES256_GCM,data:hsg=,iv:Zd46+o0v61J3X+KQ7iPHywOh/RWgP6sbKSBzGAsQAV0=,tag:zy8mab9lkTkNIuKyv9asTA==,type:int]
jwt:
    alg: ENC[AES256_GCM,data:z4qUnVI=,iv:rF2Yi8IN0I3Z8Bio9TVGgCbgZeBLjocMtbt/cFCgv4s=,tag:EYVVw9/odBWeHVbvSpENoA==,type:str]
    jwk:
        crv: ENC[AES256_GCM,data:rTCBHeI=,iv:7Jofmm54WZIcTsQCqRAI/uWog9QXAmubJPcr6JsQulg=,tag:u6KbWIznjxSsPvhTd0ncyg==,type:str]
        d: ENC[AES256_GCM,data:McXURFLoYiBJLrm82UmORx783LkXHNG7o+kVZ9Isr76wOwBLYwH6cpjnCfzILXgHoBI1ve/N/XsL+/kX+z9KqQ==,iv:sZYuHgKWf9j48Poe+zZL29wHYcIXZBtBg9wqYpFqVSA=,tag:abcaDa9WqoayHrttTnSa5Q==,type:str]
        kty: ENC[AES256_GCM,data:E88=,iv:Jy/TXAaHI6V9Qm3SLQ1Rav6Hpf1XO65HJfcaZFU+sAE=,tag:+tV83ZCg9/OvjByt/0/oWw==,type:str]
        x: ENC[AES256_GCM,data:ZzxWgM+q+/PwJ+2bQWqvPkVHfoy9yIGFZpNXy6A3jho3VwTJC50oz+nsurdxQcBlvae7pjGR3S24Y5Az+bQCHw==,iv:lIVn/mHka9D6ao5vAyC9r+V39OqY8P9FeE2PUSXMMGQ=,tag:NTXa+wM++QxY1AUlGrODrQ==,type:str]
        "y": ENC[AES256_GCM,data:01e/AIMcaCgSDNjeMBUBtTHLksjr32lYIPjGsbWtpShgtBHMsxWWd1mZ9ukJBhNrwr9vLwnAZNhusqYyqMQNCQ==,iv:1olA8BvbB0HV9aaFxtPi0Tat3HzZU9NNlgf3mJQ8wjs=,tag:8nFrMXGKeiKlJRK1/+04AQ==,type:str]
jwt_secret: ENC[AES256_GCM,data:6OViiTGcfEvzm7EmR/Cx2cKM7xFVfMl06BKGQlBIq9c=,iv:Fyj2xNCKcnlXwmn8toFy4xjxpbuj11gJ+e9HFKmM+9I=,tag:/zCL/Qo40U/PmrrHwmmxTw==,type:str]
latest_donations_count: ENC[AES256_GCM,data:Sxs=,iv:oW39tSKyymGnuQnnFMbu2qox1fXzbG+F1A5jyj9zeTI=,tag:R2rqasflXSDeDSS6Z+zxNw==,type:int]
lnd:
    lnurl_base_url: ENC[AES256_GCM,data:UCrnhH0HuoQouQXusDiZxzb1eg==,iv:UNTtnusNlNb0NRgxY6k+xocArqrq6KuT1rcmh+EzBj8=,tag:jkcvDDRuhLFI+8tEOPGziw==,type:str]
    url: ENC[AES256_GCM,data:nWDUF2+OsvpzIc19TBqI,iv:AzBScML2SHNIDRWXRN02mSqDSgbMfW7A6DCbKJ/02fw=,tag:wZUPFBu9YKIVZ40Aid+UMw==,type:str]
lnurlp:
    max_sendable_sats: ENC[AES256_GCM,data:6xFwRQ4Q6w==,iv:ZI5Msm2f0ZYPw2UfX4qrVurgPJ7sspa5tayoqTlOUCM=,tag:INVFDkA1E2tUkrDiAwavwA==,type:int]
    min_sendable_sats: ENC[AES256_GCM,data:G/o=,iv:fETMeZsbZD+1obifVfVwcTrsHT58CJF/gQ7dO7BlKKU=,tag:q8S+YFg/3asjvV387UcI9w==,type:int]
log:
    disable_existing_loggers: ENC[AES256_GCM,data:0kKUDQM=,iv:LzdnQZSm4pqlnzV8+9crucpcQwUGBB6Jj/wEpjbZpnQ=,tag:sPajpIt9JhsZ8KppGfp0GQ==,type:bool]
    formatters:
        std:
            format: ENC[AES256_GCM,data:REJ7Jt51buAfQdsSEtJLHZ5Mx7BwNy4m3wSBqZiENAZX1OBMA2vASqLWE6G1sZP9QA==,iv:OcBch4It/FBUnvcZxAjFCDn0BvzZtl1JAfax7ll6XWo=,tag:/7FOqSpcK3A1E4W1nGLQoA==,type:str]
    handlers:
        stderr:
            class: ENC[AES256_GCM,data:2/EO0mWdh84N+Z9oG7B+8/Bn+aNe,iv:ZHcnM2S07thzauYtUQyuqLJH7et5wWZ6BjzI3fP5awQ=,tag:37pfl1Z4uHMoGFPMuRHMjg==,type:str]
            formatter: ENC[AES256_GCM,data:WicB,iv:r+RJKR24svF/kxXJoklKOme3wwcSt55mXvlRElo4PZs=,tag:Z7wD81bWvjRmwPjDC60HRQ==,type:str]
            level: ENC[AES256_GCM,data:fHRhK7U=,iv:Gc3R+lV5y+C1lIonM4NVYCPCuIu40yOx8PWoLMkX5Jw=,tag:enWXNNhop7utmRljOfnvkA==,type:str]
            stream: ENC[AES256_GCM,data:+oSP1pKipwq2aMrXNfnjQg==,iv:l3R046lMz/goNpJHsxJ2Td04bbwHZVnljhoXpj8xPX4=,tag:i0/kc0MS2UY7lia9HsQLRA==,type:str]
    loggers:
        donate4fun:
            level: ENC[AES256_GCM,data:JPvBXTk=,iv:vANG8O99V58ciZNMlg93838k3uwCuuhIpKiXdHGgKSY=,tag:naYmJiLt0l1KlBduEj7klQ==,type:str]
        hypercorn:
            level: ENC[AES256_GCM,data:GNy2ToU=,iv:QXU8fgEA+C7uvO2PI9GKUlWf99pwOw0uhOThu82eC+U=,tag:rHrL6xo8Z0TP3nbwdlwnBQ==,type:str]
        sqlalchemy.engine.Engine:
            level: ENC[AES256_GCM,data:cQZ3/Fk4zQ==,iv:FEV/3Gmm9SQPKUtAEnGQSqPd00DMGeZyN03NmgHquCs=,tag:LxFkKbEwA1eNC7ZaWaBRzA==,type:str]
    root:
        handlers:
            - ENC[AES256_GCM,data:RDgMnanM,iv:4JNj4unedet/+7ABKOCuBCWos1rlEZ4MNVheBAL4Y0Y=,tag:YQ0NFUe/AfIb9n3K46G3fg==,type:str]
        level: ENC[AES256_GCM,data:Hglx3+k=,iv:i5Gc8RflFQ3GXVRL98pSyTu3PJAB2zOBZNx9p1Dfmsc=,tag:AO5IZdcbq14MHC73ZaGYpQ==,type:str]
        propagate: ENC[AES256_GCM,data:+NKQ/g==,iv:Gs5tlF3r8gSXj0Jj8XLwGI0mMxWMu9UVOH8sUGjznhk=,tag:vs95C5Y1U7d821kxGFSAvA==,type:bool]
    version: ENC[AES256_GCM,data:+Q==,iv:tZGQYPwGMfagej0TsOnF44gbfcHVi2vBX0UXpSESlOw=,tag:IceaF336IDmL+FcrmTRZhA==,type:int]
min_withdraw: ENC[AES256_GCM,data:LNI=,iv:/GOAHQvXwtIDAc4szFHWq1jWTWJJzr+S7TKU4aT0K2c=,tag:cImLlTAO/qqKsFeliFBXZg==,type:int]
ownership_message: ENC[AES256_GCM,data:y5g1sn28A7IJw30d6UGTd8BRubisEvQtgO5YanlNFRY9RXvJsclOlXxdskR3sE4bZBEyt3BN8NRJ6Je9Frn5QdhG7v2Q9UuDJ9hPvtQ=,iv:7IahB9hyTVMgufDbY0wwRm7MA23WONheCCaALk7+vXg=,tag:Ky9RvzZStDdd9Jh5d1aI4Q==,type:str]
posthog:
    host: ENC[AES256_GCM,data:jvPsUPkLtoNV9MrCHW7d2U8mV8Obag==,iv:zhweaacge0E4N+C3K2CCbuYXSOEL8Zq2ZGX288IHUGs=,tag:Z4dt0fgCvSHHwaY47ly1aw==,type:str]
    project_api_key: ENC[AES256_GCM,data:tvRiUpvf7t5AHJqHBAiJzgRhSZua2PvysB0pemn/VqPrtqFwgMrvsp4JZv3bZoY=,iv:GPTsPoECtHt61T17H/ZKZCr96xe6oxlqnhxLthD2Jvk=,tag:jPFSDsdZPVc/pIriKWjnWg==,type:str]
release: ENC[AES256_GCM,data:+3k1uA==,iv:2OZxMK2DpBMK50RNOK2gt9ThmNYsQMsJHN34uDo6qmY=,tag:Ic4DKsYXFK3zEMXFCoLHcw==,type:bool]
sentry:
    dsn: ENC[AES256_GCM,data:/1rkMWQhmpHO+mfJKDZSfH8qFlNtKQ/JV6BpyMbVi/YQgSQDOJSJha0goQOVeesC9vLsVT4IRhYLNtV7nwfaJYu6rd5P49Rl9Dx5myWR2DwJ/9gLMM03MZQvJ8k=,iv:LJnFhNwqBcft3oZDX1g6Gv2CpHmGqiesYJUTIOJwntU=,tag:gpdl3jOgiAlA/D014YKgQw==,type:str]
    environment: ENC[AES256_GCM,data:2X011w==,iv:GgaGHLEi381R1ALl6YfyRbX3TR2m1AZuspioVbYu2GI=,tag:xv9hlhR+5KYPkmqRlULz/A==,type:str]
    traces_sample_rate: ENC[AES256_GCM,data:sItYJw==,iv:xc8M7z6/7kKclCK/JSauDkDNSzvitSiFiG7IugC1kXA=,tag:wQI9XIEFZvHu1QyUAjAJMw==,type:float]
twitter:
    bearer_token: ENC[AES256_GCM,data:vILoT/pDU12vcZAWMUnqaX3g1t5EAGxePptv9IegHtCexy1App32xcYdrhLJBpKmVhdtf0M2SrH6U+vBkpUxjLD5JCRzOKIXUa3fAWR76GMHywBT+GV/xotSYoMtzSCKHQEcIJCd7/wFmV/WwIzAhQ==,iv:48kQ+u+kceZYYs8OVt+BiIJG93R1CIvRGxyDjVH3MoY=,tag:J/I0eaAbGp3lYTeMy6JDmw==,type:str]
    dm_check_interval: ENC[AES256_GCM,data:LH/p8Ks=,iv:CC5EnwNCrCn+c4pLa/51PPY/W7lXJiY67OxKRmvk5lo=,tag:0dFfd933ej93VsHJjYYH9Q==,type:str]
    enable_bot: ENC[AES256_GCM,data:h6nVB6g=,iv:ItlJV76hgs6twJRWlPf25HWDcUXaDUGndme0PRjbITE=,tag:fjCK+c26ioeD8WWXiXy00A==,type:bool]
    greeting: ENC[AES256_GCM,data:gNrZk+F32MFB4zLGaOQLBmD/NpemJvNA0P2RExbssK+kegkyMQto8SxRIxlwIJ7uUry4f2eoQnrBjEzbx4kMag/WlFP7nns2fJa0N59jq7w=,iv:yxntOc/zOP1A+qM3irE/JwYVPRX5QpQACd3NV9FlbQw=,tag:Yh9cUcqooCvmobBbUZ1Wsg==,type:str]
    oauth:
        client_id: ENC[AES256_GCM,data:tnXsBivRFXFdA4Wlc+WwTAdpRt5CgCWBvCurhKAlDBI1zw==,iv:x7dPweIOdT5zH+B3Qf+pgu+6LBNMor0fOUmqI4KlTHo=,tag:hc1Yf7r1xjmrhUGbY6OtUA==,type:str]
        client_secret: ENC[AES256_GCM,data:NbWhVQzm4jmM2sy3mXVpqvO1954sqRaQio8Dho1v4ZvuEVmIrjaRHVppxNkvfsoAFvY=,iv:G+SdMflFFBIINBAkGs3sTtR0JjHWTnwDf2q8c4dTiS8=,tag:bInkDkYPPOfk8flcBXrIjA==,type:str]
        consumer_key: ENC[AES256_GCM,data:ok0EPQbGfiv+g5oBf/Abb9ZTcOisOQGHDQ==,iv:n2ZDcG6q4SvyWChRViEVByCZn5bxbvBTQhyj0j72PKU=,tag:xJL1eMSIJcGrwjzUnTNyfg==,type:str]
        consumer_secret: ENC[AES256_GCM,data:rht1FrZEnyEi4lkGRkjKhzeTB/Ye3VZZuC7IvepBTtYsxQwBdxx1FATE7y+xNCtSNRU=,iv:hC8NMJPhuKccpN72V46cPTnAZNTsRQ4sShuw2QxSSwY=,tag:sLlmTxeqf28MU8oKsSkR2g==,type:str]
    refresh_timeout: ENC[AES256_GCM,data:i3hX,iv:jEEnls7Rmv0o1t9RlBhNNWOnXqiKSy6us3S6w9lL/pY=,tag:KRJIyVE3HNQTwmo4pyP87w==,type:str]
    self_id: ENC[AES256_GCM,data:MbiqrQnxYcn4amXQfL9rVShS/A==,iv:4hv36X3OLDpUM1FD4wEM5pGzHRgSpXHEiRSGVNF3UtI=,tag:rQfv1CcG6Os48IN4YNcErQ==,type:str]
withdraw_timeout: ENC[AES256_GCM,data:uBQ=,iv:XjP3PbeHdsCy1THUs4CDM8Ru9kEWON9OfmZgAttr3dY=,tag:EvYepBeo3m0CpU5AXqmrsA==,type:int]
youtube:
    api_key: ENC[AES256_GCM,data:AOews+N0dQLGRbmnXIrzpeUvAfHxRo7o9DznNhUDUi39gyo1cjcz,iv:ZLgr8WQgRf8S6RNg/MrUYE6pPNz8VVVqa7bGtwm8BBg=,tag:SPpT2jzDM2TSFEXrlvBFAg==,type:str]
    oauth:
        client_id: ENC[AES256_GCM,data:OyggKQ4nhKLYozGA5Hqysz+cO+JZa1UsX/B0dw48y7z2puGmHMnWDkA6BiYAyUmpB8ICiM8gzG0OUSEcemEnN8DW9lVDQFHE,iv:2mP+R1D83RwRvQUSpX0DImbKXjeXg2ZgPj/iLVbbam0=,tag:3BGP3xL8CksNTXCG3tq+uQ==,type:str]
        client_secret: ENC[AES256_GCM,data:5E6GMlik4d3X+QO4dxmoarng52eU5fys0VibxiGY2wKzoyE=,iv:GFnt2tUFHe2zRJ8VLQKol0l/XIhoGT8XyB/X2fJ1Yvs=,tag:wu/hGKif9krxludtCSlc3g==,type:str]
    refresh_timeout: ENC[AES256_GCM,data:BekR,iv:Xpm/Aoczw3rNKrJzbbc1CZPEZB8V30Was0cjtnVAKko=,tag:i2mNq2vnfqLZmut+rFBj3g==,type:str]
    service_account_key_file: ENC[AES256_GCM,data:TWYEIQdylsJoQu7RYR1tpKbqlB7y69YOYagmLw==,iv:kVexWNRZzYZjuwCaTIegenFE9rijdJYMmaY2HRbVM0o=,tag:tatkCuaJJeVXC4IqaFgUqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-01T19:31:07Z"
    mac: ENC[AES256_GCM,data:ZCq0fTTInW8mdJwCKBn0umlwOvVQ0Kj/oL+YLfzZHjVMmdRMrTuiTRB6kJy9CFXLnk6IWlTUkKPRI3md6PP1CEfbNY0m2RMEoEbylZgz1fZpEdV4Pjw5G5YQmH45kWOx8GogDtqxoKtw0m9u1MTgxYFZS6U562gDSnsWYSvn9Mg=,iv:GCsZltwvewSmKcb1qXMe8+244mcOVrquUYgDvQG14iA=,tag:+HC32FN1H8NFmLdNH0z2PA==,type:str]
    pgp:
        - created_at: "2023-09-01T19:31:07Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DNqNIbivFYBESAQdAROAk3MtBnD/bFYmi73S5VqfU/SwazoiQpYW/0hHu0lcw
            SuFnk4TWUIAELi+oW7/vtUrFTR/wqLySjSLN5y1y/I9jxCqGPWOuDFLA+lw3X4gJ
            0l4ByNKpSf+WJGLo59GX35ePe8ysRJySg7Kve/zOq1ECpjn8BdJ/6T3tt2LRLwUJ
            G7ofXzqZ4LlYURDQHne5Af72C3V4uJutMZ3edbXirZGIerGk4jP/jYp1+pACzj+E
            =IpF7
            -----END PGP MESSAGE-----
          fp: AED0C93CCCA016E7F1615FEE36A3486E2BC56011
    unencrypted_suffix: _unencrypted
    version: 3.7.3
