# Default values for donate4fun.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: ClusterIP

imagePullSecrets: []
replicaCount: 1
backend:
  port: 8080
  image:
    repository: ""
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  resources:
    limits:
      cpu: 150m
      memory: 412Mi
    requests:
      cpu: 150m
      memory: 412Mi
frontend:
  port: 8081
  image:
    repository: ""
    pullPolicy: IfNotPresent
    tag: ""
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
version: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
