name: Browser Extension

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build-extension:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extensions/src

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: ./frontend

      - name: Install extension dependencies
        run: pnpm install

      - name: Build extensions
        run: pnpm build

      - name: Archive firefox production zip file
        uses: actions/upload-artifact@v3
        with:
          name: firefox
          path: extensions/dist/firefox

      - name: Archive chrome production zip file
        uses: actions/upload-artifact@v3
        with:
          name: chrome
          path: extensions/dist/chrome
