name: Build frontend Docker-image

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: europe-central2-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          tags: europe-central2-docker.pkg.dev/donate4fun-prod/docker/donate4fun-frontend:latest
